### ISSUE TITLE
404 page should not be the index page

### ISSUE THREAD

**Issue by atridgedcosta** [bigdatr/bigdatr-startr#2]
https://github.com/bigdatr/bigdatr-startr/blob/master/generators/app/templates/server/_server.js#L43

When server is handling 404's, should not be sending the index html.

A case for this would be if `/api/futureModule/testEndpoint` didn't exist, do we need to send back html when most likely the expected response is JSON?

**Comment by allanhortle** [comment]
resolved in #12
